# We publishLocal the maven plugin instead of compile to check the maven plugin integration
matrix:
  SBT_RUN:
    - sbt "+bridgeIntegration/cachedPublishLocal" \
          "benchmarks/compile" \
          "setupIntegrations" \
          "git status" \
          "runTests" \
          "git status" \
          "backend/test" \
          "frontend/test"

  SBT_PUBLISH:
    - sbt "set pgpPublicRing in Global := file(\"/drone/.gnupg/pubring.asc\")" \
          "set pgpSecretRing in Global := file(\"/drone/.gnupg/secring.asc\")" \
          ";backend/releaseEarly;frontend/releaseEarly;^sbtBloop/releaseEarly"

  SBT_RELEASE:
    - sbt "frontend/updateHomebrewFormula" \
          "frontend/githubRelease"

clone:
  git:
    image: plugins/git
    tags: true
    recursive: true
    depth: 50

pipeline:
  restore_cache:
    image: appleboy/drone-sftp-cache
    secrets: [ sftp_cache_username, sftp_cache_private_key, sftp_cache_server, sftp_cache_path ]
    restore: true
    mount:
      - /drone/.ivy2/cache
      - /drone/.coursier
      - /drone/.sbt

  build:
    image: scalaplatform/scala:2.1
    when:
      ref: [ refs/heads/master, refs/tags/*, refs/pull/* ]
    commands:
      - git log | head -n 20
      - ${SBT_RUN}
      - ./bin/ci-clean-cache.sh

  publish:
    image: scalaplatform/scala:2.1
    secrets: [ sonatype_user, sonatype_password, pgp_password ]
    volumes:
      - /scalacenter:/keys
    when:
      ref: [ refs/heads/master, refs/tags/* ]
      event: [ push, tag, deployment ]
      status: success
    commands:
      - git log | head -n 20
      # I have no idea why this has to be done manually... TODO: inspect why.
      - export DRONE_DIR="/drone"
      - /usr/local/bin/setup_keys.sh
      - ${SBT_PUBLISH}
      - ./bin/ci-clean-cache.sh

  release:
    image: scalaplatform/scala:2.1
    secrets: [ bloopoid_github_token ]
    volumes:
      - /scalacenter:/keys
    when:
      ref: [ refs/heads/master, refs/tags/* ]
      event: [ tag ]
      status: success
    commands:
      - echo "oauth = $BLOOPOID_GITHUB_TOKEN" > ~/.github
      - ${SBT_RELEASE}

  rebuild_cache:
    image: appleboy/drone-sftp-cache
    secrets: [ sftp_cache_username, sftp_cache_private_key, sftp_cache_server, sftp_cache_path ]
    rebuild: true
    mount:
      - /drone/.ivy2/cache
      - /drone/.coursier
      - /drone/.sbt
