# We publishLocal the maven plugin instead of compile to check the maven plugin integration
matrix:
  SBT_RUN:
    - sbt "benchmarks/compile" \
          "frontend/integrationSetUpBloop" \
          "backend/test" \
          "frontend/test" \
          "docs/makeSite"

  SBT_PUBLISH:
    - sbt "set pgpPublicRing in Global := file(\"/drone/.gnupg/pubring.asc\")" \
          "set pgpSecretRing in Global := file(\"/drone/.gnupg/secring.asc\")" \
          "docs/ghpagesPushSite" \
          "releaseBloop"

  SBT_RELEASE:
    - sbt "frontend/updateHomebrewFormula" \
          "frontend/githubRelease"

clone:
  git:
    image: plugins/git
    tags: true
    # We clone the submodules ourselves
    recursive: false
    depth: 50

pipeline:
  clone:
    image: plugins/git
    when:
      ref: [ refs/heads/master, refs/tags/*, refs/pull/*/head ]
    commands:
      - ./bin/ci-clone.sh

  restore_cache:
    image: appleboy/drone-sftp-cache
    when:
      ref: [ refs/heads/master, refs/tags/*, refs/pull/*/head ]
    secrets: [ sftp_cache_username, sftp_cache_private_key, sftp_cache_server, sftp_cache_path ]
    restore: true
    mount:
      - /drone/.ivy2/cache
      - /drone/.coursier
      - /drone/.sbt

  build:
    image: scalacenter/scala-docs:1.1
    when:
      ref: [ refs/heads/master, refs/tags/*, refs/pull/*/head ]
    commands:
      - export DRONE_DIR="/drone"
      - git log | head -n 20
      - ./bin/add-coursier.sh
      - . bin/detect-community-build.sh # We need to source it for the env variable to be exported
      - ${SBT_RUN}; ./bin/ci-clean-cache.sh
     #- case "$DRONE_COMMIT_MESSAGE" in 
        #*[DOCS]*) echo "Skipping tests for commit that only changes docs." ;;
        #*) ${SBT_RUN}; ./bin/ci-clean-cache.sh ;;
        #esac

  publish:
    image: scalacenter/scala-docs:1.1
    secrets: [ sonatype_user, sonatype_password, pgp_password, bintray_user, bintray_pass, bloopoid_private_key ]
    volumes:
      - /scalacenter:/keys
    when:
      ref: [ refs/heads/master, refs/tags/* ]
      event: [ push, tag, deployment ]
      status: success
    commands:
      - git log | head -n 20
      # I have no idea why this has to be done manually... TODO: inspect why.
      - export DRONE_DIR="/drone"
      - ./bin/add-coursier.sh
      - /usr/local/bin/setup_keys.sh
      - ./bin/ci-setup-bloopoid-keys.sh
      - ${SBT_PUBLISH}
      - ./bin/ci-clean-cache.sh

  release:
    image: scalacenter/scala-docs:1.1
    secrets: [ bloopoid_github_token ]
    volumes:
      - /scalacenter:/keys
    when:
      ref: [ refs/heads/master, refs/tags/* ]
      event: [ tag ]
      status: success
    commands:
      - export DRONE_DIR="/drone"
      - ./bin/add-coursier.sh
      - echo "oauth = $BLOOPOID_GITHUB_TOKEN" > ~/.github
      - ${SBT_RELEASE}

  rebuild_cache:
    image: appleboy/drone-sftp-cache
    when:
      ref: [ refs/heads/master, refs/tags/*, refs/pull/*/head ]
    secrets: [ sftp_cache_username, sftp_cache_private_key, sftp_cache_server, sftp_cache_path ]
    rebuild: true
    mount:
      - /drone/.ivy2/cache
      - /drone/.coursier
      - /drone/.sbt
