function _projects
    bloop autocomplete --format bash --mode projects 2> /dev/null
end

function _commands
    bloop autocomplete --format bash --mode commands 2> /dev/null; or _notStarted
end

function _notStarted
    echo "server"
end

function _boolean
    echo "true false"
end

function _reporters
    bloop autocomplete --format bash --mode reporters
end

function _protocols
    bloop autocomplete --format bash --mode protocols
end

function _testsfqcn
    set -l cmd (commandline -poc)
    set -e cmd[1]
    set -l project $cmd[2]
    bloop autocomplete --format bash --mode testsfqcn --project $project
end

function _mainsfqcn
    set -l cmd (commandline -poc)
    set -e cmd[1]
    set -l project $cmd[2]
    bloop autocomplete --format bash --mode mainsfqcn --project $project
end

function __assert_args_count -a count
    set -l cmd (commandline -poc)
    set -e cmd[1]
    test (count $cmd) -eq $count
end

function __assert_args_at_least_count -a count
    set -l cmd (commandline -poc)
    set -e cmd[1]
    test (count $cmd) -ge $count
end

function _project_commands
    bloop autocomplete --format bash --mode project-commands 2> /dev/null
end

function __fish_seen_subcommand_from_project_commands
    set -l prj (string split ' ' (_project_commands))
    __fish_seen_subcommand_from $prj
end

# Nothing has been provided yet. Complete with commands
complete -c bloop -f -n "__assert_args_count 0" -a '(_commands)'

# Only a project command has been provided
complete -c bloop -f -n "__assert_args_count 1; and __fish_seen_subcommand_from_project_commands" -a '(_projects)'

########################################################################################################################
# Flags for sub-commands. From here on, this file was generated by bloop.util.FishCompleteGenerator (see developer docs)
########################################################################################################################

# BEGINNING OF GENERATED CONTENT
# complete for about
complete -c bloop -f -n "__assert_args_at_least_count 1; and __fish_seen_subcommand_from about" -l config-dir -d "File path to the bloop config directory, defaults to `.bloop` in the current working directory."
complete -c bloop -f -n "__assert_args_at_least_count 1; and __fish_seen_subcommand_from about" -l version -d "If set, print the about section at the beginning of the execution. Defaults to false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 1; and __fish_seen_subcommand_from about" -l verbose -d "If set, print out debugging information to stderr. Defaults to false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 1; and __fish_seen_subcommand_from about" -l no-color -d "If set, do not color output. Defaults to false." -xa 'true false'

# complete for autocomplete
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from autocomplete" -l config-dir -d "File path to the bloop config directory, defaults to `.bloop` in the current working directory."
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from autocomplete" -l version -d "If set, print the about section at the beginning of the execution. Defaults to false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from autocomplete" -l verbose -d "If set, print out debugging information to stderr. Defaults to false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from autocomplete" -l no-color -d "If set, do not color output. Defaults to false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from autocomplete" -l mode
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from autocomplete" -l format
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from autocomplete" -l command
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from autocomplete" -l project  -xa '(_projects)'

# complete for bsp
complete -c bloop -f -n "__assert_args_at_least_count 1; and __fish_seen_subcommand_from bsp" -l protocol -d "The connection protocol for the bsp server. By default, local." -xa '(_protocols)'
complete -c bloop -f -n "__assert_args_at_least_count 1; and __fish_seen_subcommand_from bsp" -l host -d "The server host for the bsp server (TCP only)."
complete -c bloop -f -n "__assert_args_at_least_count 1; and __fish_seen_subcommand_from bsp" -l port -d "The port for the bsp server (TCP only)."
complete -c bloop -f -n "__assert_args_at_least_count 1; and __fish_seen_subcommand_from bsp" -l socket -d "A path to a socket file to communicate through Unix sockets (local only)."
complete -c bloop -f -n "__assert_args_at_least_count 1; and __fish_seen_subcommand_from bsp" -l pipe-name -d "A path to a new existing socket file to communicate through Unix sockets (local only)."
complete -c bloop -f -n "__assert_args_at_least_count 1; and __fish_seen_subcommand_from bsp" -l config-dir -d "File path to the bloop config directory, defaults to `.bloop` in the current working directory."
complete -c bloop -f -n "__assert_args_at_least_count 1; and __fish_seen_subcommand_from bsp" -l version -d "If set, print the about section at the beginning of the execution. Defaults to false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 1; and __fish_seen_subcommand_from bsp" -l verbose -d "If set, print out debugging information to stderr. Defaults to false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 1; and __fish_seen_subcommand_from bsp" -l no-color -d "If set, do not color output. Defaults to false." -xa 'true false'

# complete for clean
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from clean" -l project -d "The projects to clean (you can specify multiple). By default, all." -xa '(_projects)'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from clean" -l include-dependencies -d "Run clean for the project's dependencies. By default, false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from clean" -l config-dir -d "File path to the bloop config directory, defaults to `.bloop` in the current working directory."
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from clean" -l version -d "If set, print the about section at the beginning of the execution. Defaults to false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from clean" -l verbose -d "If set, print out debugging information to stderr. Defaults to false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from clean" -l no-color -d "If set, do not color output. Defaults to false." -xa 'true false'

# complete for compile
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from compile" -l project -d "The project to compile (will be inferred from remaining cli args)." -xa '(_projects)'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from compile" -l incremental -d "Compile the project incrementally. By default, true." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from compile" -l pipeline -d "Pipeline the compilation of modules in your build. By default, false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from compile" -l reporter -d "Pick reporter to show compilation messages. By default, bloop's used." -xa '(_reporters)'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from compile" -l watch -d "Run the command when projects' source files change. By default, false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from compile" -l config-dir -d "File path to the bloop config directory, defaults to `.bloop` in the current working directory."
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from compile" -l version -d "If set, print the about section at the beginning of the execution. Defaults to false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from compile" -l verbose -d "If set, print out debugging information to stderr. Defaults to false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from compile" -l no-color -d "If set, do not color output. Defaults to false." -xa 'true false'

# complete for configure
complete -c bloop -f -n "__assert_args_at_least_count 1; and __fish_seen_subcommand_from configure" -l threads -d "(deprecated) Set the number of threads used to compile and test all projects."
complete -c bloop -f -n "__assert_args_at_least_count 1; and __fish_seen_subcommand_from configure" -l config-dir -d "File path to the bloop config directory, defaults to `.bloop` in the current working directory."
complete -c bloop -f -n "__assert_args_at_least_count 1; and __fish_seen_subcommand_from configure" -l version -d "If set, print the about section at the beginning of the execution. Defaults to false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 1; and __fish_seen_subcommand_from configure" -l verbose -d "If set, print out debugging information to stderr. Defaults to false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 1; and __fish_seen_subcommand_from configure" -l no-color -d "If set, do not color output. Defaults to false." -xa 'true false'

# complete for console
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from console" -l project -d "The project to run the console at (will be inferred from remaining cli args)." -xa '(_projects)'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from console" -l incremental -d "Compile the project incrementally. By default, true." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from console" -l pipeline -d "Pipeline the compilation of modules in your build. By default, false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from console" -l reporter -d "Pick reporter to show compilation messages. By default, bloop's used." -xa '(_reporters)'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from console" -l exclude-root -d "Start up the console compiling only the target project's dependencies." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from console" -l config-dir -d "File path to the bloop config directory, defaults to `.bloop` in the current working directory."
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from console" -l version -d "If set, print the about section at the beginning of the execution. Defaults to false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from console" -l verbose -d "If set, print out debugging information to stderr. Defaults to false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from console" -l no-color -d "If set, do not color output. Defaults to false." -xa 'true false'

# complete for help
complete -c bloop -f -n "__assert_args_at_least_count 1; and __fish_seen_subcommand_from help" -l config-dir -d "File path to the bloop config directory, defaults to `.bloop` in the current working directory."
complete -c bloop -f -n "__assert_args_at_least_count 1; and __fish_seen_subcommand_from help" -l version -d "If set, print the about section at the beginning of the execution. Defaults to false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 1; and __fish_seen_subcommand_from help" -l verbose -d "If set, print out debugging information to stderr. Defaults to false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 1; and __fish_seen_subcommand_from help" -l no-color -d "If set, do not color output. Defaults to false." -xa 'true false'

# complete for link
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from link" -l project -d "The project to run (will be inferred from remaining cli args)." -xa '(_projects)'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from link" -l main -d "The main class to link. Leave unset to let bloop select automatically."
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from link" -l incremental -d "Compile the project incrementally. By default, true." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from link" -l pipeline -d "Pipeline the compilation of modules in your build. By default, false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from link" -l reporter -d "Pick reporter to show compilation messages. By default, bloop's used." -xa '(_reporters)'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from link" -l watch -d "If set, run the command whenever projects' source files change." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from link" -l optimize -d "Optimization level of the linker. Valid options: `debug` or `release` mode. Defaults to `debug`."
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from link" -l config-dir -d "File path to the bloop config directory, defaults to `.bloop` in the current working directory."
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from link" -l version -d "If set, print the about section at the beginning of the execution. Defaults to false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from link" -l verbose -d "If set, print out debugging information to stderr. Defaults to false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from link" -l no-color -d "If set, do not color output. Defaults to false." -xa 'true false'

# complete for projects
complete -c bloop -f -n "__assert_args_at_least_count 1; and __fish_seen_subcommand_from projects" -l dot-graph -d "Print out a dot graph you can pipe into `dot`. By default, false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 1; and __fish_seen_subcommand_from projects" -l config-dir -d "File path to the bloop config directory, defaults to `.bloop` in the current working directory."
complete -c bloop -f -n "__assert_args_at_least_count 1; and __fish_seen_subcommand_from projects" -l version -d "If set, print the about section at the beginning of the execution. Defaults to false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 1; and __fish_seen_subcommand_from projects" -l verbose -d "If set, print out debugging information to stderr. Defaults to false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 1; and __fish_seen_subcommand_from projects" -l no-color -d "If set, do not color output. Defaults to false." -xa 'true false'

# complete for run
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from run" -l project -d "The project to run (will be inferred from remaining cli args). Requires Node.js to be in $PATH for Scala.js." -xa '(_projects)'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from run" -l main -d "The main class to run. Leave unset to let bloop select automatically." -xa '(_mainsfqcn)'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from run" -l incremental -d "Compile the project incrementally. By default, true." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from run" -l pipeline -d "Pipeline the compilation of modules in your build. By default, false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from run" -l reporter -d "Pick reporter to show compilation messages. By default, bloop's used." -xa '(_reporters)'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from run" -l args -d "The arguments to pass in to the main class."
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from run" -l watch -d "If set, run the command whenever projects' source files change." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from run" -l optimize -d "If an optimizer is used (e.g. Scala Native or Scala.js), run it in `debug` or `release` mode. Defaults to `debug`."
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from run" -l config-dir -d "File path to the bloop config directory, defaults to `.bloop` in the current working directory."
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from run" -l version -d "If set, print the about section at the beginning of the execution. Defaults to false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from run" -l verbose -d "If set, print out debugging information to stderr. Defaults to false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from run" -l no-color -d "If set, do not color output. Defaults to false." -xa 'true false'

# complete for test
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from test" -l project -d "The project to test (will be inferred from remaining cli args)." -xa '(_projects)'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from test" -l include-dependencies -d "Run tests for the project dependencies. By default, false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from test" -l incremental -d "Compile the project incrementally. By default, true." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from test" -l pipeline -d "Pipeline the compilation of modules in your build. By default, false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from test" -l only -d "The list of test suite filters to test for only."
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from test" -l args -d "The arguments to pass in to the test framework."
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from test" -l reporter -d "Pick reporter to show compilation messages. By default, bloop's used." -xa '(_reporters)'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from test" -l watch -d "Run the command when projects' source files change. By default, false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from test" -l config-dir -d "File path to the bloop config directory, defaults to `.bloop` in the current working directory."
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from test" -l version -d "If set, print the about section at the beginning of the execution. Defaults to false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from test" -l verbose -d "If set, print out debugging information to stderr. Defaults to false." -xa 'true false'
complete -c bloop -f -n "__assert_args_at_least_count 2; and __fish_seen_subcommand_from test" -l no-color -d "If set, do not color output. Defaults to false." -xa 'true false'